version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UIVERSION}
    ports:
      - ${UIPORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:

  