version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UIVERSION}
    ports:
      - ${UIPORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:

  