---
# vars file for gitlab-runner
gitlab_runner_tags:
        - linux
        - xenial 
        - ubuntu
        - docker
gitlab_runner_docker_image: 'alpine:latest'
gitlab_runner_registration_token: 'thVTr1dFC9ztZn5hrm3V'
gitlab_runner_docker_volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "/srv/gitlab-runner/config:/etc/gitlab-runner"
gitlab_runner_executor: docker
gitlab_runner_coordinator_url: http://35.198.173.231/
gitlab_runner_description: 'Artemkin Example GitLab Runner'



